DECLARE
    v_email CLIENTE.EMAIL%TYPE;
BEGIN
    SELECT EMAIL INTO v_email FROM cliente;

    DBMS_OUTPUT.PUT_LINE('EL CORREO DEL CLIENTE ES: '||v_email);

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ASOCIADOS');

    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('LA CONSULTA DEVUELVE MAS DE UN DATO');
END;
/
--DIVICION POR ZERO 

DECLARE
    V_RESULTADO NUMBER;
BEGIN
    V_RESULTADO := 100/0;
EXCEPTION
    WHEN ZERO_DIVIDE THEN
        DBMS_OUTPUT.PUT_LINE('NO SE PUEDE DIVIDIR POR CERO');

END;
/

DECLARE
BEGIN

END;