DECLARE
    TYPE asientos_cine IS VARRAY(6) OF VARCHAR2(3);

    V_asientos asientos_cine := asientos_cine('A1','A2','A3','A4','A5');

BEGIN
    DBMS_OUTPUT.PUT_LINE('SE LE ASIGNO EL ASIENTO N°'|| V_asientos(3));
    NULL;
END;
/

--UNO CON RUT
DECLARE
    TYPE RUTS_CLIENTES IS VARRAY(3) OF VARCHAR2(12);

    V_RUT RUTS_CLIENTES := RUTS_CLIENTES('21.717.999-8','22.818.888-7','23.919.777-6');
BEGIN
    DBMS_OUTPUT.PUT_LINE('EL RUT DEL PRIMER CLIENTE ES: '||V_RUT(1));
END;
/

--UNO PROCEDURAL
DECLARE
    TYPE RUTS_CLIENTES IS VARRAY(4) OF VARCHAR2(12);

    V_RUT_CLIENTES RUTS_CLIENTES := RUTS_CLIENTES();
BEGIN
    V_RUT_CLIENTES.EXTEND;
    V_RUT_CLIENTES(1) := '21.717.999-8';

    V_RUT_CLIENTES.EXTEND;
    V_RUT_CLIENTES(2) := '22.818.888-9';

    V_RUT_CLIENTES.EXTEND;
    V_RUT_CLIENTES(3) := '23.919.777-7';

    V_RUT_CLIENTES.EXTEND;
    V_RUT_CLIENTES(4) := '20.777.888-9';

    DBMS_OUTPUT.PUT_LINE(V_RUT_CLIENTES(1));
    DBMS_OUTPUT.PUT_LINE(V_RUT_CLIENTES(2));
    DBMS_OUTPUT.PUT_LINE(V_RUT_CLIENTES(3));
    DBMS_OUTPUT.PUT_LINE(V_RUT_CLIENTES(4));
END;
/